schemaVersion: 2.0.0
commandTests:
  - name: "Node v14"
    command: "node"
    args: ["-v"]
    expectedOutput: ["v14"]
  - name: "Git v2 installed"
    command: "git"
    args: ["--version"]
    expectedOutput: ["git version 2"]
